name: "ssh-job"
description: "Execute any script through ssh"
author: "Marcin Jałocha"
inputs:
  host:
    required: true
    description: "Target machine hostname or ip"
  port:
    required: true
    description: "Port to use while connecting"
    default: "22"
  key:
    description: "Ssh private key used to connect to target machine"
  passphrase:
    required: false
    description: "Passphrase for the private key"
  user:
    description: "Ssh user"
  password:
    description: "Ssh password"
  envs:
    description: "Environment variables passed to the shell script"
  ignoredEnvs:
    description: "Environment variables that are ommited from passing to the shell"
  command:
    required: true
    description: "Bash commands ran on target machine"
  exportActionOptions:
    required: false
    description: "Export all action options to shell script"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "terminal"
  color: "gray-dark"
